version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-local
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    container_name: express-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://admin:secret@mongo:27017/?authSource=admin
    depends_on:
      - mongo